### ISSUE TITLE
PRECISA CORREÇÃO

### ISSUE THREAD

**Issue by evssousa** [davitkblade/lista-de-albuns#1]
Prestar atenção no nome dos repositórios, devem está igual aos dos projetos.

**Comment by davitkblade** [comment]
CORRIGIDO!

**Comment by evssousa** [comment]
Não foi encontrado link no "Reserve sua viagem".

**Comment by evssousa** [comment]
Erro 404

**Comment by davitkblade** [comment]
ambos os erros foram corrigidos.
